pref("extensions.tagger.rename.keepextension", true);
pref("extensions.tagger.rename.keepcopy", false);
pref("extensions.tagger.rename.pattern", "%a/%??b/%a - %??n %t");
pref("extensions.tagger.retag.autoupcase", false);
pref("extensions.tagger.retag.keeptags", true);
pref("extensions.tagger.retag.lastfmt", "");
pref("extensions.tagger.retag.replace_", true);
pref("extensions.tagger.retag.dirsupport", false);
pref("extensions.tagger.settags.keeptags", true);
pref("extensions.tagger.firstrun", true);
pref("extensions.tagger.filterfilenames", true);
pref("extensions.tagger.filter.replace", true);
pref("extensions.tagger.filter.replacement", " ");